name: Deploy ANDROID ElectroPlan

on:
  push:
    branches:
      - android-app-redesign

jobs:
  ftp-deploy-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Android branch
        uses: actions/checkout@v4

      - name: Deploy Android branch to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.ANDROID_FTP_USERNAME }}
          password: ${{ secrets.ANDROID_FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          dangerous-clean-slate: false
